version: '3'

services:
  # Service pour l'application Spring Boot
  app:
    build: .
    ports:
      - "8091:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/stocks?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sabrine
      SPRING_JPA_OPEN-IN-VIEW: false

  # Service pour la base de données MySQL
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sabrine
      MYSQL_DATABASE: stocks
